services:
  - type: web
    name: lealtix-dashboard
    env: static
    staticPublishPath: dist/lealtix_dashboard
    buildCommand: npm run build
    routes:
      # Redirige la ra√≠z hacia /auth/login
      - type: redirect
        source: /
        destination: /auth/login
        statusCode: 302

      # Permite que Angular maneje las rutas internas
      - type: rewrite
        source: /*
        destination: /index.html
